website/models.py
from flask import current_app, g
from flask_mysqldb import MySQL

def get_db():
    if 'db' not in g:
        g.db = current_app.extensions['mysql'].connection.cursor()
    return g.db

def close_db(e=None):
    db = g.pop('db', None)

    if db is not None:
        db.close()

website/__init__.py
from flask import Flask
from flask_mysqldb import MySQL

mysql = MySQL()

def create_app():
    app = Flask(__name__)

    # Add the secret key
    app.config['SECRET_KEY'] = 'fjdkslkdjf qsmeizeoiuez qaputqsmapht sapzeirusksjf'


    # Configuration de la base de données MySQL
    app.config['MYSQL_HOST'] = 'localhost'
    app.config['MYSQL_USER'] = 'root'
    app.config['MYSQL_PASSWORD'] = ''
    app.config['MYSQL_DB'] = 'flaskapp1_db'
    app.config['MYSQL_PORT'] = 3306
    app.config['MYSQL_UNIX_SOCKET'] = None
    app.config['MYSQL_CONNECT_TIMEOUT'] = 10
    app.config['MYSQL_READ_DEFAULT_FILE'] = None
    app.config['MYSQL_READ_DEFAULT_GROUP'] = None
    app.config['MYSQL_CLIENT_FLAGS'] = None
    app.config['MYSQL_CHARSET'] = None
    app.config['MYSQL_USE_UNICODE'] = True
    app.config['MYSQL_SQL_MODE'] = None
    app.config['MYSQL_CURSORCLASS'] = None
    app.config['MYSQL_SSL_KEY'] = None
    app.config['MYSQL_SSL_CERT'] = None
    app.config['MYSQL_SSL_CA'] = None
    app.config['MYSQL_SSL_CAPATH'] = None
    app.config['MYSQL_SSL_CIPHER'] = None

    mysql.init_app(app)

    from .views import views
    from .auth import auth

    app.register_blueprint(views, url_prefix='/')
    app.register_blueprint(auth, url_prefix='/')

    return app

website/auth.py
from flask import Blueprint, render_template, redirect, request, session, url_for, flash
from . import mysql

auth = Blueprint('auth', __name__)

@auth.route('/login', methods=["POST", "GET"])
def login():
    if request.method == "POST":
        data = request.form
        name = data.get('name')
        password = data.get('password')

        cur = mysql.connection.cursor()
        cur.execute("SELECT * FROM users WHERE username = %s AND password = %s", (name, password))
        user = cur.fetchone()
        cur.close()

        if user:
            session['username'] = user[1]
            return redirect(url_for('views.dashboard'))
        else:
            flash('Invalid username or password', category='error')
            return redirect(request.url)

    else:
        if 'username' in session:
            return redirect(url_for('views.dashboard'))
        return render_template('login.html')

@auth.route('/logout')
def logout():
    session.pop('username', None)
    return redirect(url_for('auth.login'))

@auth.route('/sign-up', methods=["POST", "GET"])
def sign_up():
    if request.method == "POST":
        data = request.form
        username = data.get('name')
        pass1 = data.get('password1')
        pass2 = data.get('password2')

        if username is None or len(username) < 4:
            flash('Username should be greater than 4 characters', category='error')
        elif len(pass1) < 7:
            flash('Password should be greater than 7 characters', category='error')
        elif pass1 != pass2:
            flash('Passwords don\'t match', category='error')
        else:
            cur = mysql.connection.cursor()
            cur.execute("INSERT INTO users (username, password) VALUES (%s, %s)", (username, pass1))
            mysql.connection.commit()
            cur.close()
            flash('Account created!', category='success')
            return redirect(url_for('auth.login'))

    return render_template('sign_up.html')

website/views.py
from flask import Blueprint, render_template, current_app, g
from . import mysql

views = Blueprint('views', __name__)


@views.route('/')
def home():
    cur = mysql.connection.cursor()
    cur.execute('SELECT * FROM users')
    data = cur.fetchall()
    cur.close()
    return render_template('home.html',data=str(data))

@views.route('/contact')
def contact():
    return render_template('contact.html')

@views.route('/about')
def about():
    return render_template('about.html')

@views.route('/privacy')
def privacy():
    return render_template('privacy.html')

@views.route('/dash')
def dashboard():
    return render_template('dashboard.html')

website/templates/about.html
{% extends "base.html" %}

{% block title %}
About Page
{% endblock %}

{% block content %}
<h1>Welcome to the About Page</h1>
<p>This is the content of the About page.</p>
{% endblock %}

website/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href=" {{ url_for('static',filename='css/bootstrap.min.css' ) }} ">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
<div class="container">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
            <a class="navbar-brand"  href="{{ url_for('views.home') }}">
                <img src="{{ url_for('static', filename='img/icon.png') }}" alt="Brand Logo">
            </a>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{{ url_for('views.home') }}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('views.contact') }}">Contact</a>
                    </li>
                    <li class="nav-item">
                        {% if session['username'] %}
                            <a class="nav-link" href="{{ url_for('auth.logout') }}">Logout</a>
                        {% elif request.endpoint != 'login' %}
                            <a class="nav-link" href="{{ url_for('auth.login') }}">Login</a>
                        {% endif %}
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('auth.sign_up') }}">Sign Up</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</div>

{% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
        {% for category, message in messages %}
            {% if category == 'error' %}
                <div class="alert alert-danger alert-dismissible fade show" role="alert">
                    {{ message }}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            {% else %}
                <div class="alert alert-success alert-dismissible fade show" role="alert">
                    {{ message }}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            {% endif %}
        {% endfor %}
    {% endif %}
{% endwith %}



    <div class="container">
        {% block content %}{% endblock %}
        
            <!-- Footer Section -->
        <footer class="bg-light text-center text-lg-start mt-4">
            <div class="container p-4">
                <div class="text-center">
                    <p>&copy; 2024 Your Company. All Rights Reserved.</p>
                    <a href="{{ url_for('views.about') }}" class="text-dark">About</a> |
                    <a href="{{ url_for('views.privacy') }}" class="text-dark">Privacy</a> |
                    <a href="{{ url_for('views.contact') }}" class="text-dark">Contact</a>
                </div>
            </div>
        </footer>
    </div>

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script> <!-- jQuery -->
    <script src=" {{ url_for('static', filename='js/bootstrap.min.js')}}"></script>
    <script src="href={{ url_for('static', filename = 'js/script.js')}}"></script>
</body>
</html>

website/templates/contact.html
{% extends "base.html" %}

{% block title %}
Contact Page
{% endblock %}

{% block content %}

<form  action="" method="" >
    <div class=" contact row gy-4">

      <div class="col-md-6">
        <input type="text" name="name" class="form-control" placeholder="Your Name" required="">
      </div>

      <div class="col-md-6 ">
        <input type="email" class="form-control" name="email" placeholder="Your Email" required="">
      </div>

      <div class="col-md-12">
        <input type="text" class="form-control" name="subject" placeholder="Subject" required="">
      </div>

      <div class="col-md-12">
        <textarea class="form-control" name="message" rows="6" placeholder="Message" required=""></textarea>
      </div>

      <div class="col-md-12 text-center">
        <div class="error-message"></div>
        <button type="submit">Send Message</button>
      </div>

    </div>
  </form><!-- End Contact Form -->


{% endblock %}

website/templates/dashboard.html
{% extends "base.html" %}

{% block title %}Dashboard{% endblock %}

{% block content %}
<div class="container">
    <h1>Dashboard</h1>
    {% if session['username'] %}
        <p> Welcome {{ session['username']|title }} </p>
    {% else %}
        <p>Welcome</p>
    {% endif %}
</div>
{% endblock %}

website/templates/home.html
{% extends "base.html" %}

{% block title %}
Home Page
{% endblock %}

{% block content %}

    <section>
        <h1> Hi,{{ session['username'] }} </h1>
        <p>{{data}}</p>
    </section>

{% endblock %}

website/templates/login.html
{% extends "base.html" %}

{% block title %}Login{% endblock %}

{% block content %}
<div class="container">
    <h1>Sign In</h1>
    <form action="{{ url_for('auth.login') }}" method="POST">
        <div class="form-group">
            <label for="name">Username</label>
            <input type="text" class="form-control" id="name" name="name" placeholder="Enter Username">
        </div>
        <div class="form-group">
            <label for="password">Password</label>
            <input type="password" class="form-control" id="password" name="password" placeholder="Password">
        </div>
        <button type="submit" class="btn btn-primary">Sign In</button>
    </form>
</div>
{% endblock %}

website/templates/privacy.html
{% extends "base.html" %}

{% block title %}Privacy Policy{% endblock %}

{% block content %}
<div class="container">
    <h1>Privacy Plicy</h1>
</div>
{% endblock %}

website/templates/sign_up.html
{% extends "base.html" %}

{% block title %}Register{% endblock %}

{% block content %}
<div class="container">
    <h1>Sign Up</h1>
    <form action="{{ url_for('auth.sign_up') }}" method="POST">
        <div class="form-group">
            <label for="name">Username</label>
            <input type="text" class="form-control" id="name" name="name" placeholder="Enter Username">
        </div>
        <div class="form-group">
            <label for="password1">Password</label>
            <input type="password" class="form-control" id="password" name="password1" placeholder="Password">
        </div>
        <div class="form-group">
            <label for="password2">Confirm Password</label>
            <input type="password" class="form-control" id="password" name="password2" placeholder="Password">
        </div>
        <button type="submit" class="btn btn-primary">Register</button>
    </form>
</div>
{% endblock %}